In [1]:
import numpy as np

In [2]:
v =  np.array([1,-1,2])

In [3]:
w = np.array([2,5,2])

In [4]:
print(v+w)

[3 4 4]


In [5]:
print(v-w)

[-1 -6  0]


In [7]:
#Scalar Multiplication
print(3*v)

[ 3 -3  6]


In [8]:
print(np.linalg.norm(v))

2.449489742783178


In [9]:
s = np.dot(v,w)

In [10]:
s

np.int64(1)